### ISSUE TITLE
./mkcvm.sh: line 1: syntax error near unexpected token `newline' ./mkcvm.sh: line 1: `<!DOCTYPE html>'

### ISSUE THREAD

**Issue by NewthanGuy** [totallyNotAUser/mkcvm#3]
./mkcvm.sh: line 1: syntax error near unexpected token `newline'
./mkcvm.sh: line 1: `<!DOCTYPE html>'

**Comment by totallyNotAUser** [comment]
Oh. now i see why the error message happens. It seems that it downloaded some html page instead of the script.

After checking the gg.gg link, I see it got blocked. I updated the README to fix the link.
